### PR TITLE
Implement proper volume functionality

### PR DESCRIPTION
**Pull request by maksimsdimov**
Now gets the number of the audio sink (spotify application) and sets the output for that specific application.

### CODE REVIEW

**Comment by pwittchen** [comment]
Hi,

Thanks for this PR! Code looks fine. I'll test it and if everything will be working, then we can merge it.

Regards,
Piotr

**Comment by maksimsdimov** [comment]
No problem, glad I could help. Thanks for the quick reply.

I only tested on Debian 9 and Ubuntu 18.04.

**Comment by pwittchen** [comment]
It doesn't work on my machine :-(. I'm using Ubuntu 18.04.2 LTS.
I see the error:
```
Nieprawidłowy indeks odpływ wejścia
```
which is:

```
Invalid outflow index
```

When I try to use it with sudo:

```
No protocol specified
xcb_connection_has_error() zwróciło wartość „true”
Home directory not accessible: Brak dostępu
Połączenie się nie powiodło: Odrzucono połączenie
pa_context_connect() się nie powiodło: Odrzucono połączenie
Traceback (most recent call last):
  File "./spotifycli.py", line 227, in <module>
    main()
  File "./spotifycli.py", line 57, in main
    control_volume("-5%")
  File "./spotifycli.py", line 215, in control_volume
    num = get_sink_number()
  File "./spotifycli.py", line 203, in get_sink_number
    out = check_output(['pactl', 'list', 'sink-inputs'])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pactl', 'list', 'sink-inputs']' returned non-zero exit status 1
```

First lines in Polish says: 

```
Returned true
No access
Connection refused
```

**Comment by maksimsdimov** [comment]
Running it with sudo is not going to work because the PulseAudio daemon is running in userspace.

Can you try with the latest changes?

**Comment by pwittchen** [comment]
Thanks. I'll test it with the latest change.

**Comment by pwittchen** [comment]
Now it works! Thanks!

**Pull request merged**
