### PR TITLE
Add azlyrics as a lyrics source

### PR DESCRIPTION
**Pull request by SigmundurMorkore**
Solves issue #56

Not sure if this azlyrics library is the best option. I had to manually change the library code because its __init__.py file had an import error...

After fixing it, it works perfectly it seems.

### CODE REVIEW

**Comment by pwittchen** [comment]
Hi,

Thanks for your PR. When lyricwikia cannot find the lyrics, I get the following error in terminal.

```
Traceback (most recent call last):
  File "./spotifycli/spotifycli.py", line 143, in show_lyrics
    lyrics = lyricwikia.get_all_lyrics(artist, title)
  File "/usr/lib/python3.8/site-packages/lyricwikia/lyricwikia.py", line 41, in get_all_lyrics
    raise LyricsNotFound('Cannot download lyrics')
LyricsNotFound: Cannot download lyrics

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./spotifycli/spotifycli.py", line 208, in <module>
    main()
  File "./spotifycli/spotifycli.py", line 42, in main
    show_lyrics()
  File "./spotifycli/spotifycli.py", line 145, in show_lyrics
    lyrics = azlyrics.lyrics(artist, title)
AttributeError: module 'azlyrics' has no attribute 'lyrics'
```

**Comment by SigmundurMorkore** [comment]
Yeah, that’s why I had to change the library’s (Azlyric’s) code manually.

I looked at azlyric’s repository now and looks like it hasn’t been updated for 2 years.

It’d probably be best to use another library.

**Comment by pwittchen** [comment]
As long as `azlyric` dependency is broken, I don't won't to include it in my project. I cannot force each script user, to manually add dependency, change source code of the dependencies, etc. I'd like to include as little dependencies as possible and included dependencies should work out of the box.

**Comment by pwittchen** [comment]
Due to broken azlyric dependency, unfortunately, I cannot merge this. Nevertheless, thanks for your PR.

**Pull request closed without merging**
